version: "3.9"

services:
  techstore-db:
    image: postgres:16-alpine
    container_name: techstore-db
    environment:
      POSTGRES_USER: techstore
      POSTGRES_PASSWORD: techstore_pwd
      POSTGRES_DB: techstore_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - techstore_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: techstore-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - techstore-db

volumes:
  techstore_data:
